# Introduction {#intro}

As traffic on freeways continues to rise, developing a reliable method to regulate the flow of vehicles onto the freeway has become increasingly important. A primary method that was first implemented in the 1960s is the ramp meter. A ramp meter is a traffic signal that is placed on the freeway on-ramp, designed to control the rate at which vehicles enter the freeway and therefore prevent it from exceeding capacity. Although ramp meters may improve freeway traffic conditions, they often generate a queue, causing vehicles to wait on the ramp prior to entering the freeway. 

Research has previously been done to estimate the queue length at freeway on-ramps, but most conclude that while certain methods improve queue size estimation, each possess shortcomings that would prevent it from being widely implemented across many ramps without significant calibration and cannot easily be used in real-time. This paper aims to improve these previously developed methods, thus providing algorithms that more accurately report the expected queue length on any given on-ramp that utilizes ramp metering. 

This paper will focus on estimating the queue length of two on-ramps in Davis and Salt Lake counties in Utah. The ramps chosen for analysis are the northbound on-ramp to I-15 at Layton Parkway in Davis County and the southbound on-ramp at Bangerter Highway in Salt Lake County.

Two methods to estimate queue length are discussed in this paper, including a conservation model and a Kalman filter model. The Kalman filter model includes several variations to find a method that most accurately reflects field-observed queue lengths. This paper will discuss methods by which both the conservation and Kalman filter models can be used to estimate queue length real-time on freeway on-ramps. Various components of the ramp such as the number of lanes, the ramp length, its traffic volume and occupancy, and the metering rate will be considered. Throughout this paper, a literature review will explain the methods previously utilized to measure ramp meter performance and queue length and the methodology used to collect and analyze the data. Following this, a discussion of the results will be presented, after which the paper will conclude with a summary of all items discussed. 