# Literature Review

When freeway operations consistently deteriorate during peak hours, ramp meters are often implemented on the on-ramp, thus regulating the flow of vehicles entering the freeway. By controlling the flow of vehicles onto the freeway, motorists can travel in more favorable traffic conditions, which can reduce crashes, improve overall travel time, and lower emissions [@papageorgiou2002freeway]. Although conditions on the freeway may improve when ramp meters are implemented, this often leads to increased wait time on the on-ramp. Several ramp metering algorithms have been used in an attempt to find a balance between freeway and ramp operations, though much remains to be accomplished (Liu et al. 2012). For example, Minnesota implemented ramp meters in 1969, and in the fall of 2000—at the request of citizens in the Minneapolis-St. Paul area—the meters were shut off for 8 weeks to analyze whether freeway conditions were superior with the ramp meters (Levinson and Zhang 2004). To the surprise of some traffic analysts, some areas of the Twin Cities showed decreased travel time without the ramp meters, though the results mostly showed that travel delay, average speed, and travel time performed significantly better with the ramp meters in use.  Other areas throughout both the United States have shown similar results. The Seattle Bottleneck algorithm, used in many locations, has also reduced crash rates and average travel time (Jacboson et al. 2006). Thus, in order to best understand the benefits of ramp meters, it is imperative that their function be established.  

There are two primary classifications of ramp meters: pre-timed meters and traffic-responsive meters (Jacobson et al. 2006). Pre-timed meters operate at a set rate based on historical data. This type of metering has proven effective when traffic volumes are easily predictable. However, when sudden changes in traffic operations occur, pre-timed meters often fail to account for the change without manual intervention. Traffic-responsive metering on the other hand relies on real-time data collection through the use of loop detectors, which can be placed within the pavement or in the form of traffic cameras. Due to the extensive amount of data being collected, the initial calibration of traffic-responsive meters can prove to be time consuming; however, once effectively implemented, they can mitigate congestion based on the data received on the ramp (Jacobson et al. 2006). 

By using loop detectors on the ramps, time occupancy and traffic volume data are gathered. Occupancy refers to the percent of time a point on the road is occupied by a vehicle; for example, if no vehicle passes over the detector during a given time period, the occupancy would be 0 percent, whereas if a vehicle was detected passing over the detector during half of that same time period, the time occupancy would show 50 percent (@wu2009experiment). Several studies have been conducted to use the data gathered by loop detectors to estimate the queue length on metered on-ramps. Vigos et al.(2006), Liu et al. (2007), and @wu2009experiment (2009) utilize the loop detector data to estimate queue length with two proposed methods, including a conservation model and a Kalman filter model. The conservation model assumes that the number of vehicles entering and exiting the ramp throughout a given time period is the same. The Kalman filter model is based on the conservation model, but uses additional ramp characteristics and a Kalman filter coefficient "K"  to improve the queue length estimate provided by the conservation model. Wu et al. (2009) also use the Highway Capacity Manual (HCM) back of queue method, however it proved to be ineffective, and will not be discussed in detail in this literature review. The original equations developed for the conservation model and Kalman filter algorithms required the volume entering and exiting the ramp to be equal, but through analysis of the data, Wu et al. (2009) found that the volumes were not balanced over time.

## Using a Volume-Balancing Ratio

Many difficulties are introduced when relying solely on ramp detector data. One difficulty in particular is that vehicles can be double-counted or missed altogether depending on the location of the vehicle passing over the detector (Wu et al. 2008). Because of this potential for error, the original conservation model equation and Kalman filter equation were modified by Wu et al. 2008 to balance the volumes entering and exiting the ramp, which is shown by a volume-balancing ratio "C" in each equation. Equation 1 is the conservation model equation with the volume-balancing ratio included, and Equation 2 and Equation 3 are the equations used for the Kalman filter method with the volume-balancing ratio. 

The Kalman filter model applied by @wu2009experiment is as follows:

\begin{equation}
q_i = q_{i-1} + c_i + k (\hat{q}_i - q_{i-1})
  (\#eq:kalman)
\end{equation}

Using the volume-balancing ratio previously mentioned, it is presumed that the conservation model and Kalman filter algorithms will produce more accurate queue length estimates, which can then be used to calculate the expected vehicle wait time. @wu2009experiment explain that the volume-balancing ratio may be set as a constant value or may be calculated in real time. Prior to incorporating this volume-balancing ratio, when @wu2009experiment utilized Equation 2 to find the queue length estimate based on the occupancy data, they found the correlation between the estimated queue length and the time occupancy to be only 0.63. This research also concluded that the relationship between volume data from the detector and the estimated number of vehicles is nonlinear, as the results gave a correlation coefficient of merely 0.18 between the two variables. Therefore, it is likely there are other factors outside the capability of this equation that affect the queue length such as detector error, driver distraction, poor weather, and traffic incidents.  

However, in analyzing 20 data sets from ramp meters in Milwaukee, Wisconsin, @wu2009experiment found that the volume-balancing ratio improved both the Kalman filter and the conservation models considerably in nearly all cases, and in only a select few cases were slightly more errors introduced. These errors were found to occur in the Kalman filter models because when the volume-balancing ratio is close to 1 (the detector volume entering and exiting the ramp are nearly equal), the Kalman filter coefficient K is also close to zero, but the equation still adds queue length to the estimate from the coefficient K, which would introduce additional error. In contrast, when the volume-balancing ratio is not close to 1, the Kalman filter equation yield more reliable results than the conservation model. Overall, @wu2009experiment found that both the Kalman filter and conservation model, especially when using the volume-balancing ratio, provide generally accurate estimates of the actual queue length. 

## Determination of K
Research previously conducted on estimating the queue length on on-ramps using a Kalman filtering method has yielded varied and generally inconclusive results with respect to which value of K should be used at any given on-ramp, especially for real-time estimation. Vigos et al. (2006) was of the first to use the Kalman filtering equation to estimate the queue length at metered on-ramps. The estimation for this research was done using microscopic simulation, and it concluded that while K ranged from [0.1, 0.25] in their analysis, the optimum value to be used for K is "0.22 for one detector and 0.5 for all other detector numbers" Vigos et al. (2006). However, no field testing was performed in this analysis. Liu et al. (2007) appears to have used a linear regression model to calculate K by using the passage and queue occupancy, and they concluded that the Kalman filter yielded the most accurate results for ramps that were determined to have significant error (larger than 2 percent) between the volume detected by queue and passage detectors. Finally, Wu et al. (2009) proposed calculating K by minimizing the root-mean sqaured error (RMSE) between the field-collected queue length and the estimated queue length with the Kalman filter for each peak period at each ramp. Wu et al. (2009) again confirm that the Kalman filter outperforms the conservation model when there is significant error between the queue and passage detectors, because the Kalman filter model can correct itself. Wu et al. (2009) confirm that the Kalman filter coefficient would require significant calibration for each ramp metering location and for each peak period. Thus, manually collected data would be required for each additional ramp that is desired to be studied, which limits the feasibility of using the Kalman filter in real-time.

## Relationship between K and Traffic Analysis Parameters
This paper will seek to expound on previously performed research by finding ways the Kalman filter coefficient K can be correlated with various traffic analysis parameters that can be calculated directly from the detector data. If a reliable correlation between these parameters and K can be found, the queue length can then calculated in real time with the Kalman filter equation.

Each metered on-ramp in Utah has three detector locations in each lane. These detectors include at the excessive queue (EQ), which is located shortly after the entrance to each ramp, the intermediate queue (IQ), located roughly in the middle of the on-ramp, and the passage queue (PQ), located directly after the ramp meter signal. Both volume and occupancy data are collected by these detectors in 60-second increments at each of these locations. The variable ramp metering rate is also updated every 60 seconds. The length of the ramp and number of lanes on the ramp are also known by observation. Using these data, additional traffic analysis parameters such as the traffic density (in units of veh/mi/ln) and flow (in units of veh/hr) can be calculated.